### ISSUE TITLE
请问如何才能让open-falcon将这个插件调度起来

### ISSUE THREAD

**Issue by tonglin0325** [mdh67899/openfalcon-monitor-scripts#1]
手动运行该脚本可以post到open-falcon上，但是必须重启open-falcon才能看到数据，open-falcon如何才能将这个脚本调度起来，每分钟运行一次

**Comment by mdh67899** [comment]
你把这个脚本放到agent的plugins某个目录下，例如放到flume目录，在portal上将机器加到组里，绑定好flume这个插件就好了

**Comment by mdh67899** [comment]
刚看到这个issue: https://github.com/open-falcon/falcon-plus/issues/435

我想问一下是否有绑定插件吗？只要绑定好插件了理论上会被agent每60调度一次的，agent的日志有没有关于这个脚本的日志？重启open-falcon才能看到数据，这个我不太理解时什么意思

**Comment by tonglin0325** [comment]
已经绑定了，不清楚绑定的有没有问题
先创建了host group ,然后修改了hosts和plugins
我插件是放在这个目录下：~/software/open-falcon-v0.2.1/agent/plugins/plugin/mdh67899/openfalcon-monitor-scripts/flume
agent的config配置："plugin": {
        "enabled": true,
        "dir": "./agent/plugins/plugin/mdh67899/openfalcon-monitor-scripts",
        "git": "https://github.com/mdh67899/openfalcon-monitor-scripts.git",
        "logs": "./logs"
    }
其次还去掉了你脚本里面post的注释
logs如下
2018/04/30 21:18:56 plugin.go:64: <Plugins:[mdh67899/openfalcon-monitor-scripts/flume], Timestamp:1525094336>
2018/04/30 21:19:00 var.go:88: => <Total=4> <Endpoint:master, Metric:rate, Type:GAUGE, Tags:name=pfc.push.cnt, Step:60, Time:1525094340, Value:0.016666634013952863>
2018/04/30 21:19:00 var.go:95: <= <Total=4, Invalid:0, Latency=0ms, Message:ok>
2018/04/30 21:19:00 var.go:88: => <Total=5> <Endpoint:master, Metric:value, Type:GAUGE, Tags:name=pfc.push.size, Step:60, Time:1525094340, Value:5>
2018/04/30 21:19:00 var.go:95: <= <Total=5, Invalid:0, Latency=0ms, Message:ok>
2018/04/30 21:19:56 var.go:88: => <Total=12> <Endpoint:master, Metric:df.bytes.free.percent, Type:GAUGE, Tags:mount=/,fstype=ext4, Step:60, Time:1525094396, Value:77.18740277840907>
2018/04/30 21:19:56 var.go:88: => <Total=87> <Endpoint:master, Metric:agent.alive, Type:GAUGE, Tags:, Step:60, Time:1525094396, Value:1>
2018/04/30 21:19:56 var.go:95: <= <Total=12, Invalid:0, Latency=0ms, Message:ok>
2018/04/30 21:19:56 var.go:88: => <Total=6> <Endpoint:master, Metric:ss.closed, Type:GAUGE, Tags:, Step:60, Time:1525094396, Value:10>
2018/04/30 21:19:56 var.go:95: <= <Total=87, Invalid:0, Latency=1ms, Message:ok>
2018/04/30 21:19:56 var.go:95: <= <Total=6, Invalid:0, Latency=0ms, Message:ok>

**Comment by mdh67899** [comment]
agent的日志里面你始终找不到我py脚本running的日志吧？

你看下./agent/plugins/plugin/mdh67899/openfalcon-monitor-scripts这个目录下面是不是有有一个flume目录，下面放着我的py脚本

如果是的话那你应该是绑定错plugin了，plugin是相对于你的plugins目录来说的，看你的配置你应该绑定flume这个plugin就可以了

**Comment by tonglin0325** [comment]
在portal里面的plugin dir我写过

**Comment by tonglin0325** [comment]
在portal里面的plugin dir我写过 flume ，也试过plugin/mdh67899/openfalcon-monitor-scripts，也写过plugin/mdh67899/openfalcon-monitor-scripts/flume，但是好像脚本都没有被调用

**Comment by tonglin0325** [comment]
我把plugin dir改成flume之后，日志里面报了error
2018/04/30 21:42:27 scheduler.go:60: agent/plugins/plugin/mdh67899/openfalcon-monitor-scripts/flume/60_flume-monitor.py running...
2018/04/30 21:42:27 plugin.go:64: <Plugins:[flume], Timestamp:1525095747>
2018/04/30 21:42:27 var.go:88: => <Total=87> <Endpoint:master, Metric:agent.alive, Type:GAUGE, Tags:, Step:60, Time:1525095747, Value:1>
2018/04/30 21:42:27 scheduler.go:71: plugin started: agent/plugins/plugin/mdh67899/openfalcon-monitor-scripts/flume/60_flume-monitor.py
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72e5e3]

goroutine 11 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/sys.CmdRunWithTimeout(0xc4204c4000, 0xdda79f300, 0x2, 0xc420192ae0, 0x0)
	/home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/sys/cmd.go:41 +0x43
github.com/open-falcon/falcon-plus/modules/agent/plugins.PluginRun(0xc420317dc0)
	/home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/plugins/scheduler.go:74 +0x276
github.com/open-falcon/falcon-plus/modules/agent/plugins.(*PluginScheduler).Schedule.func1(0xc420317de0)
	/home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/plugins/scheduler.go:35 +0xc4
created by github.com/open-falcon/falcon-plus/modules/agent/plugins.(*PluginScheduler).Schedule
	/home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/plugins/scheduler.go:41 +0x3f

**Comment by mdh67899** [comment]
没被调用说明agent把plugins和plugin组合后没找到这个全目录下的脚本

你是怎么启动agent的，启动时的所处的目录和plugins目录在同一个目录下面吗？

你把dirs的路径写成绝对路径，确保flume下有脚本，重启再试一下

**Comment by mdh67899** [comment]
看日志脚本的确被调用了，这个报错不看代码还真不知道是什么问题，你试一下把agent升级到最新版本试试

**Comment by tonglin0325** [comment]
确实修改之后已经可以调用到你的脚本了，但是每次./open-falcon stop 再./open-falcon start后启动后，日志都会报错，然后check，结果是agent挂掉了，使用的版本是v0.2.1

**Comment by mdh67899** [comment]
我去，看agent日志执行脚本的时候不知道为什么引用了空指针，然后agent就崩溃了

看你的版本貌似有点老，保证脚本有可执行权限，单独更新agent版本再试试

如果还有问题麻烦贴一下全部日志，我去看看源码

**Comment by tonglin0325** [comment]
下的已经是最新的包了，地址 v0.2.1
https://github.com/open-falcon/falcon-plus/releases
接下来可能会考虑根据报的日志查查原因，或者换v0.2.0的版本试试
谢谢你的开源脚本和指导，有问题再请教

**Comment by mdh67899** [comment]
好的，你确保脚本改对了，agent确实能调度脚本的情况下再试试吧，可以试着从master最新代码build一个二进制文件再试试，始终搞不懂为啥agent会崩溃掉

**Comment by tonglin0325** [comment]
在重新下了open-falcon源码自己打包后成功调度了你的脚本，期间遇到了[ERROR] exec plugin plugin/flume/60_flume-monitor.py fail. error: exec: not started的问题，发现脚本只有读权限，在修改了文件的mod之后成功调度了，问题全部解决，十分感谢
